# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def dz_pods  
  use_frameworks!

  # Pods for DailyZap
  pod "InitialsImageView"
  pod 'PopupDialog', '~> 0.6'
  pod 'Flurry-iOS-SDK/FlurrySDK'
#  pod 'Flurry-iOS-SDK/FlurryAds'
  pod 'Google-Mobile-Ads-SDK'
end

target 'DailyZap' do
  dz_pods
  # Copy to Beta and Test Target
  target 'DailyZapTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
target 'Beta-DailyZap' do
  dz_pods
end
