# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DailyZap' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DailyZap
  pod "InitialsImageView"
  pod 'PopupDialog', '~> 0.6'
#  pod 'SACountingLabel'
  pod 'Flurry-iOS-SDK/FlurrySDK'
  target 'Beta-DailyZap' do
    inherit! :search_paths
  end
  target 'DailyZapTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
