# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do


  desc "Build and upload Testflight"
  lane :beta do
    build_app(scheme: "DailyZap",
    	      workspace: "DailyZap.xcworkspace",
	      export_options: {
	        provisioningProfiles: {
		  "com.dqlobo.DailyZap" => "iPhone Developer"
		}
	      },
	      codesigning_identity: "iOS Developer",
	      include_bitcode: true)
  end


end
